name: Update extinct-sounds.com

on:
  push:
    branches: [ main ]

jobs:
    
  build:

    runs-on: ubuntu-20.04
    steps:

    - uses: actions/checkout@v3

    - name: Use Node.js v16.18.0
      uses: actions/setup-node@v3
      with:
        node-version: 16.18.0
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    - name: CI Step
      run: npm ci
      working-directory: ./website

    - name: Build Production
      run: CI=false REACT_APP_WALLET_CONNECT_PROJECT_ID=${{ secrets.REACT_APP_WALLET_CONNECT_PROJECT_ID }} npm run build
      working-directory: ./website

    - name: Assume IAM User
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Push to S3
      run: aws s3 sync build/ s3://extinct-sounds
      working-directory: ./website

    - name: Assume IAM Role
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
